### PR TITLE
Test for lazy OneToOne associations

### PR DESCRIPTION
**Pull request by DavideD**
From the conversation on Zulip

### CODE REVIEW

**Review by gavinking — APPROVED** [review]
Thanks!

**Comment by DavideD** [comment]
It seems it doesn't work for all the dbs. I will check

**Comment by DavideD** [comment]
It seems that MariaDB has some problems with UUID types used as query parameters. I've changed the test entities to a `Long id`.
It should work now.

**Comment by gavinking** [comment]
Do we still have tests for UUID elsewhere?

**Comment by gavinking** [comment]
Oh, of course, you only changed the new test. Sorry.

**Comment by DavideD** [comment]
> Oh, of course, you only changed the new test. Sorry.

Yes, I will check this as well in a bit.
Is it me or every  time I work an on issue, I find 3 other different ones? :-)

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/674

**Comment by gavinking** [comment]
Pretty sure that's normal.

**Pull request merged**
