### PR TITLE
rename selectLong() to selectIdentifier()

### PR DESCRIPTION
**Pull request by gavinking**
And add a comment about batching, to make its semantics clear.

### CODE REVIEW

**Comment by DavideD** [comment]
Awesome!
Since you are changing this area, can we also change `updateReturning` to `insertSelectIdentity`,  or something similar?

**Comment by gavinking** [comment]
> Since you are changing this area, can we also change `updateReturning` to `insertSelectIdentity`, or something similar?

I *guess*, but I feel like it's a bit more general than that. In this case this method is general-purpose, for *any* DML that returns a value.

`selectIdentifier()` OTOH now has rather special semantics.

**Comment by DavideD** [comment]
I don't think it's that generic.

The `updateReturning` method has a condition that if the query doesn't return any value, it will call `getMySqlLastInsertedId`. Plus it returns a `Long`

**Comment by DavideD** [comment]
We could also move the MySQL logic in the class generating the identity. It might make more sense

**Comment by gavinking** [comment]
Ah, you have a good point. 

OK, fine, I will rename it.

**Comment by gavinking** [comment]
> We could also move the MySQL logic in the class generating the identity. It might make more sense

Nah I'm hoping to keep that logic nicely contained in there because it will surely change at some stage when Vert.x figures out a better/more general way to do this.

**Review by DavideD — APPROVED** [review]

**Pull request merged**
