### PR TITLE
[#143] Set the tag of the docker images to use

### PR DESCRIPTION
**Pull request by DavideD**
Otherwise we rely on whatever version TestContainer uses as default
  and it's not always the latest or could change between updates.

  I decided to use the family version where available but we might
  want to change this in the future and use the exact version to be
  extra safe.

### CODE REVIEW

**Comment by aguibert** [comment]
Historically Testcontainers never changes the default label for exactly this reason -- updating could break users. But I still think it's a good idea to explicitly specify the version so that our docker (testcontainers) and podman devs are always using the same DBs

**Comment by DavideD** [comment]
I really don't understand the way they choose defaults in TestContainers. If they never update the tag why not always use the latest and clarify it in the javadoc?

Anyway, @aguibert  did you also build the PR? GitHub seems to have some problem and cannot test it with the actions

**Comment by gavinking** [comment]
> GitHub seems to have some problem and cannot test it with the actions

The CI is busted since the change to the DB2 database name.

**Comment by DavideD** [comment]
Thanks, I will check

**Comment by DavideD** [comment]
Something was wrong with GitHub. It's working now.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/146

**Pull request closed without merging**
