### PR TITLE
Upgrade databases dependencies

### PR DESCRIPTION
**Pull request by DavideD**
Db2 to 11.5.6.0
MariaDB to 10.6.2
CockroachDB to 21.1.5
Postgres to 13.3 (where it was still 13.2)

### CODE REVIEW

**Comment by gavinking** [comment]
👍

**Comment by Sanne** [comment]
Strange failures. I've restarted the CI tests.

**Comment by DavideD** [comment]
THere's something not quite right with db2... as usual

**Comment by Sanne** [comment]
I've also had loads of issues with DB2 containers. I don't think it's worth keep updating it w/o a good reason, when you have a working version.

Revert the DB2 upgrade, upgrade the others?

**Comment by DavideD** [comment]
I've removed the commit with Db2

**Comment by DavideD** [comment]
Merged without Db2

**Pull request merged**
