### PR TITLE
Upgrade to Vert.x 4.1

### LINKED ISSUE #673: EagerOneToOneAssociationTest fails on CI with Vert.x SQL client 4.0.3
After the upgrade to Vert.x SQL Client 4.0.3,  `EagerOneToOneAssociationTest ` fails if the whole test suite is launched on Db2.
For example:
```
./gradlew testDbDb2 -Pdocker
```

will cause (I've enabled logging of the queries):
```
Gradle Test Executor 18 > org.hibernate.reactive.EagerOneToOneAssociationTest > testPersist STANDARD_OUT
    INFO Dialect [vert.x-worker-thread-0] HHH000400: Using dialect: org.hibernate.dialect.DB297Dialect                                                                                                                
    INFO ReactiveIntegrator [vert.x-worker-thread-0] HRX000001: Hibernate Reactive Preview
    INFO DefaultSqlClientPool [vert.x-worker-thread-0] HRX000011: SQL Client URL [jdbc:db2://localhost:50000/hreact:user=hreact;password=hreact;]
    INFO DefaultSqlClientPool [vert.x-worker-thread-0] HRX000012: Connection pool size: 5             
    INFO DefaultSqlClientPool [vert.x-eventloop-thread-0] HRX000013: Detected driver [io.vertx.pgclient.spi.PgDriver]
    INFO DefaultSqlClientPool [vert.x-eventloop-thread-0] HRX000013: Detected driver [io.vertx.mysqlclient.spi.MySQLDriver]                      
    INFO DefaultSqlClientPool [vert.x-eventloop-thread-0] HRX000013: Detected driver [io.vertx.db2client.spi.DB2Driver]
    [Hibernate] drop table Author251s]                                                                                                                                                                                
    [Hibernate] drop table Book2                                                                                                                                                                                      
    [Hibernate] drop table Author2                                                                                                                                                                                    
    WARN GenerationTargetToDatabase [vert.x-eventloop-thread-0] HRX000021: DDL command failed [io.vertx.db2client.DB2Exception: The object 'HREACT.AUTHOR2' provided is not defined]
    [Hibernate] drop table Book2        
    WARN GenerationTargetToDatabase [vert.x-eventloop-thread-0] HRX000021: DDL command failed [io.vertx.db2client.DB2Exception: The object 'HREACT.BOOK2' provided is not defined]
    [Hibernate] create table Author2 (id integer not null, name varchar(255), mostPopularBook_id integer, primary key (id))                                                        
    [Hibernate] create table Book2 (id integer not null, title varchar(255), author_id integer, primary key (id))
    [Hibernate] alter table Author2 add constraint FK2g039ym91gfrw4qpe3u012hh0 foreign key (mostPopularBook_id) references Book2                                                          
    [Hibernate] alter table Book2 add constraint FK98y4jhffatmiyfaboqc4muu3p foreign key (author_id) references Author2
    [Hibernate] select eageroneto_.id, eageroneto_.mostPopularBook_id as mostpopu3_0_, eageroneto_.name as name2_0_ from Author2 eageroneto_ where eageroneto_.id=?
                                                                                                                                                                                                                      
Gradle Test Executor 18 > org.hibernate.reactive.EagerOneToOneAssociationTest > testPersist STANDARD_ERROR                                                                                                            
    java.lang.IndexOutOfBoundsException: index: 432, length: 1 (expected: range(0, 432))
        at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1390)
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1397)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1384)                                                                                                                                                                                                                                                                                                                                                            
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1379)
        at io.netty.buffer.AbstractByteBuf.getByte(AbstractByteBuf.java:355)
        at io.vertx.db2client.impl.codec.DB2Decoder.computeLength(DB2Decoder.java:62)                                                                                                                                                                                                                                                                                                                                                       
        at io.vertx.db2client.impl.codec.DB2Decoder.decode(DB2Decoder.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)                     
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)                                                                                                                     
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)                              
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)         
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)        
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)    
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)                                                                                                                                
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)                                                                                                                      
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)                                                                                                                                               
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)        
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                                                                                      
        at java.base/java.lang.Thread.run(Thread.java:834)                                                                                                                                                            
                                                                                                           
Gradle Test Executor 18 > org.hibernate.reactive.EagerOneToOneAssociationTest > testPersist FAILED
    java.util.concurrent.TimeoutException                                  
        at io.vertx.ext.unit.impl.TestContextImpl.lambda$run$1(TestContextImpl.java:79)                                                                                                                                                                                                                                                                                                                                                     
        at java.base/java.lang.Thread.run(Thread.java:834)

```

it also seems that we don't catch the exception in our tests suite, instead of failing, it goes in timeout.
To see the actual exception, change the `testLogging` configuration in [hibernate-reactive-core/build.gradle](https://github.com/hibernate/hibernate-reactive/blob/a3f4c61eef71baab8ca321da5af0bfb9052bde4b/hibernate-reactive-core/build.gradle#L78) to:
```
testLogging {
        ...
        showStandardStreams = true
        ...
    }
```

Here's the PR that shows the exception: https://github.com/hibernate/hibernate-reactive/pull/670

I've created an issue on Vert.x SQL Client: https://github.com/eclipse-vertx/vertx-sql-client/issues/916

### LINKED ISSUE #697: Re-enable tests for Db2
Because of [a bug in the Vert.x SQL client](https://github.com/eclipse-vertx/vertx-sql-client/issues/920)

This is the commit that disables the tests: https://github.com/hibernate/hibernate-reactive/commit/d76bb7217e5580d1e387506ca332406bf3ec7768

It should work once we upgrade to Vert.x SQL client 4.1.0

### LINKED ISSUE #739: Sometimes the build goes in timeout because of an exception
Occasionaly, builds with Db2 fail because [of a bug in the Vert.x Db2 client](https://github.com/eclipse-vertx/vertx-sql-client/issues/920). This bug has been already fixed and it should disappear when we will upgrade to Vert.x 4.1.

The problem is that, when it happens, our build get stuck and goes in timeout, even if a real error happened.
I suspect we are swallowing an exception somewhere in one of the classes related to the connection. 

An example of this behaviour is at this commit: d3d46c4f63fe227558a46028d3cfbf2661759ed0
The build will get stuck on Db2:
```
./gradlew clean testDbDb2
```

The real exception is visible setting  `showStandardStreams = true` in the gradle build.

### LINKED ISSUE #799: Upgrade to Vert.x 4.1
Vert.x just released version 4.1.0.CR1.

This will bring us the improved thread pool management and the fix for the index  out of bound errors with DB2

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #799 
Fixes #697 
and (indirectly)
Fixes #673

### CODE REVIEW

**Comment by gavinking** [comment]
I'm surprised: I thought the new pool model was going to require significant changes to our connection handling?

**Comment by gavinking** [comment]
> I thought the new pool model was going to require significant changes to our connection handling?

Or was that only to the Quarkus extension?

**Comment by DavideD** [comment]
We made those changes here: https://github.com/hibernate/hibernate-reactive/commit/c60bb8d02d2bfcb57330bc873036a1c208a29833

My understanding is that they are compatible with 4.0 but the real benefits come with 4.1.
Anyway, I could have upgraded before releasing yesterday... but I forgot

**Comment by gavinking** [comment]
Oh so you mean we're already using 4.1 in Quarkus?

**Comment by DavideD** [comment]
@Sanne ^

**Comment by gavinking** [comment]
@DavideD you can also reenable `EmptyCompositeCollectionKeyTest`.

(But not `OrderedEmbeddableCollectionTest` which is a different bug in the driver.)

**Comment by DavideD** [comment]
> you can also reenable `EmptyCompositeCollectionKeyTest`.

Done

**Comment by Sanne** [comment]
> Oh so you mean we're already using 4.1 in Quarkus?

yes, it's using `4.1.0.CR1` since yesterday

**Comment by gavinking** [comment]
Alright, then let's go!

**Pull request merged**
