### PR TITLE
Add StatelessSession#setBatchSize

### LINKED ISSUE #1056: Add setBatchSize to the stateless session

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #1056

### CODE REVIEW

**Comment by gavinking** [comment]
You realize `StatelessSession` doesn't have any setter methods ... because it's supposed to be "stateless"....

I wonder if there's some other way we could handle this: like, implicitly turning on batching when you use `persistAll()`/`updateAll()`....

**Comment by DavideD** [comment]
I didn't think the batchSize was considered part of the state. In Hibernate ORM Stateless has a setJdbcBatchSize(https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/SharedSessionContract.java#L194).

**Comment by gavinking** [comment]
Sure, it's very arguable :-)

But even so, I guess I feel like it would fall more in line with the whole philosophy and feel of `StatelessSession` to make it an optional argument of the `xxxxxAll()` methods.

As a user I would find that more convenient, frankly.

**Comment by gavinking** [comment]
The reason it's an attribute for regular sessions is that the user doesn't have fine control over updates. Here they do.

**Comment by DavideD** [comment]
Alright, I will try to add it as an optional parameter

**Comment by DavideD** [comment]
@gavinking I've applied the changes we've discussed

**Comment by gavinking** [comment]
OK, great, LGTM

**Pull request merged**
