### PR TITLE
#417 Update to Vert.x 4

### PR DESCRIPTION
**Pull request by DavideD**
This is not supposed to be merged.
The idea is to create a separate branch upstream calle `vert.x-4`.

### CODE REVIEW

**Comment by DavideD** [comment]
I've removed the workflow for the latest Vert.x sql client 4 because it causes some error

**Comment by gavinking** [comment]
@DavideD so Vert.x 4 has a whole different approach to to managing transactions?

**Comment by DavideD** [comment]
It seems so, the Transaction is not a `SQLClient` anymore so you cannot return it like we did before.
To be fair, I put together this fix quite quickly and I have to give it a better look, but I think it could work for an initial branch

**Comment by DavideD** [comment]
Also `beginConnection()` returns a `Future<Transaction>` instead of a `Transaction`. It makes sense to me but I'm wondering if we should should change our `SQLClientConnection#beginTransaction()` to return a `CompletionStage<Transaction>` instead of `CompletionStage<Void>`. Just a feeling. That's what I would expect by looking at the method for the first time.

But I'm surprise and quite happy to see that all the tests pass with this simple patch.

**Comment by Sanne** [comment]
+1 to track Vertx.next , but remember to keep these dependencies in synch with what's in Quarkus.

**Comment by DavideD** [comment]
Sure, we don't plan to include this in the main branch for now.

**Comment by DavideD** [comment]
It's seems everybody is cool with this, I'm going to push it upstream

**Comment by Sanne** [comment]
upstream? in its own branch?

**Comment by DavideD** [comment]
Yes

**Comment by DavideD** [comment]
Branch created upstream

**Pull request closed without merging**
