### PR TITLE
introduce SqlClientPoolConfiguration

### PR DESCRIPTION
**Pull request by gavinking**
Allow the user to micromanage the pool configuration via a plug-in service.

Solves use cases like #304.

### CODE REVIEW

**Comment by guy1699** [comment]
Hi @gavinking,
I'm struggling with SSL on Hibernate reactive, 
I'm having both Hibernate reactive and non-reactive on the same Spring app, using the same Postgres url+user+password.
But only the reactive one throw an error: 
`io.vertx.pgclient.PgException: FATAL: no pg_hba.conf entry for host "44.200.242.24", user "auivdmhgrqdqjt", database "d96r68n8o6d7g2", SSL off (28000)`

This is how I generate the factories:

```
 @Bean
    public LocalSessionFactoryBean sessionFactory() {
        LocalSessionFactoryBean sessionFactory = new LocalSessionFactoryBean();
        sessionFactory.setDataSource(dataSource());
        sessionFactory.setPackagesToScan("com.salesforce.atrium.core.model");
        sessionFactory.setHibernateProperties(hibernateProperties());

        return sessionFactory;
    }

    @Bean
    public Mutiny.SessionFactory reactiveSessionFactory() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory(PERSISTENCE_UNIT_NAME, hibernateReactiveProperties());
        Mutiny.SessionFactory reactiveSessionFactory = emf.unwrap(Mutiny.SessionFactory.class);
        return reactiveSessionFactory;
    }
```

Also asked that question in [StackOverflow](https://stackoverflow.com/questions/70517702/where-to-define-ssl-connection-with-hibernate-reactive).

**Comment by gavinking** [comment]
That's _waaaay_ outside my area of even superficial knowledge. Perhaps the vert.x guys might be able to help you.

**Comment by guy1699** [comment]
Reallyyyy, I thought this was the original issue, [configuring SSL on Vertx](https://github.com/hibernate/hibernate-reactive/issues/304).
So it is not the Hibernate team responsibility, the gap between Hibernate non reactive (`org.springframework.orm.hibernate5.LocalSessionFactoryBean`) and reactive one (`org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl`)...

Can you point to the Vert.x support/github please?

**Comment by DavideD** [comment]
@guy1699 The different channels for asking questions on Vert.x: https://vertx.io/channels/

**Comment by gavinking** [comment]
> So it is not the Hibernate team responsibility

Well no, Hibernate Reactive doesn't know anything about SSL.

That's precisely the reason I introduced `SqlClientPoolConfiguration`: so that _you_ can write code to do whatever needs to be done using the Vert.x APIs directly.

**Comment by guy1699** [comment]
Thanks guys.
Closing.

**Pull request merged**
