### PR TITLE
[#257] batch inserts

### PR DESCRIPTION
**Pull request by gbadner**
https://github.com/hibernate/hibernate-reactive/issues/257

### CODE REVIEW

**Comment by gbadner** [comment]
The current commits are preliminary work for supporting execution of a batched update directly on a `ReactiveConnection`.

@gavinking, is this what you are expecting? Provided that it is, my plan is to move onto implementing a `ReactiveBatchBuilder` which will extend ORM's `BatchBuilder` `Service`, and get it incorporated into hibernate-reactive.

**Comment by gavinking** [comment]
> @gavinking, is this what you are expecting? 

Yep, precisely!

**Comment by gavinking** [comment]
Hi @gbadner, did you make any further progress on this? Anything I can do to help?

**Comment by gbadner** [comment]
@gavinking, I'm sorry but I did not get any farther on this.

**Comment by gavinking** [comment]
Closing this PR because it's superseded by #312.

Note that I did use commit 1a593c8.

**Pull request closed without merging**
