### PR TITLE
Improve ProxyConnection error handling

### PR DESCRIPTION
**Pull request by stuartwdouglas**
- Add better error message if it has been closed
- Don't explicity throw the exception, return a failed CS instead

### CODE REVIEW

**Comment by DavideD** [comment]
@gavinking How come [`ReactiveConnection#close()` ](https://github.com/hibernate/hibernate-reactive/blob/65ff89ad5594e36cb2152bf08a2ef0c6807b2bdc/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java#L64) doesn't return a `CompletionStage<Void>`?

**Comment by DavideD** [comment]
I'm asking because `ProxyConnection` delegates to `SqlClientConnection` and it seems to me that we should add the same logic in that class as well.

**Comment by gavinking** [comment]
> @gavinking How come [`ReactiveConnection#close()` ](https://github.com/hibernate/hibernate-reactive/blob/65ff89ad5594e36cb2152bf08a2ef0c6807b2bdc/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/ReactiveConnection.java#L64) doesn't return a `CompletionStage<Void>`?

Well I guess because we wanted `Session.close()` to be synchronous, and because in Vert.x 3, `SqlClient.close()` was synchronous.

Looks like it returns a `Future` in Vert.x 4, and so we have a problem :-(

**Comment by DavideD** [comment]
I suppose we can change it for the next release?

**Comment by gavinking** [comment]
> I suppose we can change it for the next release?

Well, we'll *have to*. But I don't see how we can fix this without changing APIs.

`Session` can't even be `AutoCloseable` now.

Ugh. Wish we had caught this sooner.

**Comment by gavinking** [comment]
Unless there's some way to do it fire-and-forget???

**Comment by gavinking** [comment]
> Unless there's some way to do it fire-and-forget???

Well, perhaps it is implicitly fire-and-forget. If I just ignore the returned `Future`, it will still get closed, right?

**Comment by gavinking** [comment]
> If I just ignore the returned `Future`, it will still get closed, right?

But then if we do that maybe the rest of our stream never gets completed?

@cescoffier @jponge need your help on understanding this one.

**Comment by DavideD** [comment]
> Well, perhaps it is implicitly fire-and-forget. If I just ignore the returned `Future`, it will still get closed, right?

It probably doesn't happen often, but a user might want to wait for the session or connection to be really closed before doing something else.

**Comment by DavideD** [comment]
> But then if we do that maybe the rest of our stream never gets completed?

What do you mean?

**Comment by gavinking** [comment]
> What do you mean?

Well TBH I'm just not clear enough on Vert.x semantics to know what happens in the case where we throw away a `Future`.

**Comment by gavinking** [comment]
> A user might want to wait for the session or connection to be really closed before doing something else.

I can't *imagine* a case where the user would care. But I admit I can't imagine everything.

**Comment by DavideD** [comment]
> Well TBH I'm just not clear enough on Vert.x semantics to know what happens in the case where we throw away a `Future`.

Isn't this more of a conceptual issue? If we don't wait for the `Future` to be completed, the connection might not have been closed when we run the next operation and we loose exceptions if something went wrong.

I wonder if this happens also when the session is closed right now.

**Comment by gavinking** [comment]
> Isn't this more of a conceptual issue? 

Absolutely it's a conceptual issue. 

That's what I'm saying, this is a potentially serious problem.

> If we don't wait for the `Future` to be completed, the connection might not have been closed when we run the next operation and we loose exceptions if something went wrong.

Well I agree we should log them at least. But I would say that the failure to return a connection to the pool when the transaction has already completed successfully is something the users of my program don't care about.

The *administrators* certainly might care, and so we should certainly log such a thing.

**Comment by DavideD** [comment]
> `Session` can't even be `AutoCloseable` now.

Is this that bad? We already have `.withSession` that does the same thing. Plus the `Autoclosable` is not for reactive things.

**Comment by gavinking** [comment]
Well, it's not a *disaster*.

**Comment by gavinking** [comment]
I mean, I don't think you can use try with resources to manage a reactive session, so if you interpret AutoClosesble as being all about that one thing, then Session shouldn't implement it anyway. (That's not clear to me.)

**Comment by DavideD** [comment]
One alternative I can think of is that we could overload `close` to something like:
```
void close(CompletableFuture<Void> closed);
```

So that a user could pass a `CompletableFuture` that we can complete when everything has been closed.
But I don't like this solution, I think it would teach bad habits and also confuse people quite a bit.

I think we should update the API.

**Comment by DavideD** [comment]
I mean, add the `CompletionStage<Void>` to the `close()` method.

**Comment by DavideD** [comment]
> I mean, I don't think you can ever use try with resources to manage a reactive session, so if you interpret AutoClosesble as being all about that one thing, then Session shouldn't implement it anyway.

+1

**Comment by gavinking** [comment]
Sure, that's probably best, but I can't help wondering why the operation of "return a connection to the pool" needs to be async in the first place. There's probably some really good reason, but I don't know what it might be.

**Comment by DavideD** [comment]
I've created https://github.com/hibernate/hibernate-reactive/issues/716

**Comment by DavideD** [comment]
Merged  https://github.com/hibernate/hibernate-reactive/pull/715, Thanks @stuartwdouglas !

**Comment by gavinking** [comment]
> Sure, that's probably best, but I can't help wondering why the operation of "return a connection to the pool" needs to be async in the first place.

Well, it looks like one reason is that if you return a connection to the pool with an open transaction, it rolls it back. I guess that's a good enough reason.

**Pull request merged**
