### PR TITLE
[910] SchemaMigrator/SchemaValidator support for MySQL and MariaDB

### PR DESCRIPTION
**Pull request by gbadner**
https://github.com/hibernate/hibernate-reactive/issues/910

Requires:
* Reactive PR: https://github.com/hibernate/hibernate-reactive/pull/903
* ORM PR: https://github.com/hibernate/hibernate-orm/pull/4106

### CODE REVIEW

**Comment by gbadner** [comment]
I've added 2 commits:

[252e482](https://github.com/gbadner/hibernate-reactive/commit/252e482a9632eb95fcaa72ac770668c0da59c7a9) fixes an off-by-one bug in `ResultSetAdapter#getXXX(int columnIndex). @gavinking, you should probably look at this one.

[11214b9](https://github.com/gbadner/hibernate-reactive/commit/11214b93ba65ad99ce4dc8580597e4d85bbdf423) adds support for MariaDB. It just uses the same code as MySQL.

**Comment by gbadner** [comment]
I forgot to say "thank you" to @blafond for helping to get things started with supporting MariaDB.

Thanks @blafond!

**Comment by gavinking** [comment]
@gbadner OK I guess we were never using lookup by column index before so I suppose that's correct.

**Comment by gbadner** [comment]
Pushed a [commit](https://github.com/hibernate/hibernate-reactive/pull/940/commits/b7d678f0a907a9166f85899725180c5ca0b4d753) to improve Javadoc and simplify MySqlReactiveInformationExtractorImpl methods

**Comment by gavinking** [comment]
@gbadner could you please rebase this on the latest main branch, which now depends on the latest ORM (which includes your work over there).

**Comment by gbadner** [comment]
I've merged the commits from this PR into https://github.com/hibernate/hibernate-reactive/pull/903, so closing this PR.

**Pull request closed without merging**
