### PR TITLE
Upgrade to Mutiny 1.3.0

### PR DESCRIPTION
**Pull request by jponge**

### CODE REVIEW

**Comment by gavinking** [comment]
Nice, I missed that :)

**Comment by jponge** [comment]
It's fresh from 10 minutes ago or so 😃

**Comment by Sanne** [comment]
@jponge is the same upgrade expected to land in Quarkus 2.7 ?

We need to ensure compatibility with Quarkus 2.7, so unless that upgrade is likely we should hold

**Comment by jponge** [comment]
@Sanne It's got merged 😃  

See https://github.com/quarkusio/quarkus/pull/22825

**Pull request merged**
