### PR TITLE
update to Mutiny 0.11.0

### PR DESCRIPTION
**Pull request by gavinking**

### CODE REVIEW

**Comment by gavinking** [comment]
What is up with the CI?

**Comment by Sanne** [comment]
I've been wondering the same, all my PRs from yesterday seem stack (my "Experiment" PRs are meant to test github actions)

**Comment by jponge** [comment]
Still not finished?

**Comment by Sanne** [comment]
@jponge I'm afraid there's something wrong with our github actions - I've had this with PRs sent yesterday as well.

Since it compiles w/o changes and most runs are fine, I'd think it's not worth for the Quarkus PR to wait for this - it's not likely to be a Mutiny problem.

**Comment by jponge** [comment]
No worries @Sanne, I'm even fine if the Quarkus PR waits a bit for validation. Hibernate Reactive is really a prime repository for `Uni` usage.

Your call 😉

**Comment by gavinking** [comment]
@Sanne I mean, is there really a good reason to not just go ahead and apply this and #446. I'm pretty sure they don't really break anything.

**Comment by gavinking** [comment]
(And the most recent push to this repo was already marked as failing.)

**Comment by Sanne** [comment]
Sure, let's apply.

**Pull request merged**
