### PR TITLE
disable ryuk for #399

### PR DESCRIPTION
**Pull request by gavinking**
Should we do this?

### CODE REVIEW

**Comment by DavideD** [comment]
I don't mind, if it makes life easier to some people I guess we can include it.

But I don't understand if this is a testcontainers bug. If it is, won't it be solved at some point?

**Comment by gavinking** [comment]
> But I don't understand if this is a testcontainers bug. If it is, won't it be solved at some point?

I believe it is, it when I looked it seemed like it will be .... but .... why do we even need this daemony thing if test containers works perfectly fine without it?

**Comment by bsideup** [comment]
I would advice against it (you don't want to have dangling containers after running the tests, do you? :)).

There was a behaviour change in one of Docker for Mac's releases that we fixed in Testcontainers 1.15.0, so I would suggest upgrading the dependency instead.

**Comment by gavinking** [comment]
Fine, then lets do #435 instead.

**Pull request closed without merging**
