### PR TITLE
Upgrade to Hibernate ORM 5.4.23.Final

### LINKED ISSUE #428: Upgrade to Hibernate ORM 5.4.23.Final
Changes: https://hibernate.atlassian.net/projects/HHH/versions/31887/tab/release-report-all-issues

### PR DESCRIPTION
**Pull request by Sanne**
Fixes #428

### CODE REVIEW

**Comment by Sanne** [comment]
The release should be available in Maven now.

**Comment by DavideD** [comment]
The build is failing with 5.5-SNAPSHOT: https://github.com/hibernate/hibernate-reactive/pull/427/checks?check_run_id=1339598262

Is it something that is going to be fixed on the ORM side or do we need to update our classes?

**Comment by Sanne** [comment]
I think I already fixed it - how do I force CI to run again?

**Comment by Sanne** [comment]
force pushed, just changing the commit message (once again) to trigger CI

**Comment by Sanne** [comment]
@DavideD all green :)

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/427

Not sure why it doesn't notice it. 

Thanks

**Pull request closed without merging**
