### PR TITLE
Test property about mapping of null Embeddables

### PR DESCRIPTION
**Pull request by blafond**
Fixes [#552](https://github.com/hibernate/hibernate-reactive/issues/552) and verifies expected behavior

### CODE REVIEW

**Comment by gavinking** [comment]
@blafond that failure on DB2 looks familiar:

https://github.com/eclipse-vertx/vertx-sql-client/issues/899

Last time I ran into this I just disabled the test on DB2.

**Comment by blafond** [comment]
Thx.  updating test now to exclude DB2

**Review by gavinking — APPROVED** [review]
LGTM!

**Comment by gavinking** [comment]
thanks!

**Pull request merged**
