### PR TITLE
[#678] Test for UUID as field type 

### PR DESCRIPTION
**Pull request by DavideD**
Doesn't fix the issue for MariaDB or MySQL but it checks that everything works for the other dbs

### CODE REVIEW

**Comment by gavinking** [comment]
I thought you were going to set the column length using @Column

**Comment by DavideD** [comment]
I've added the test for MariaDB and MySQL with the column defition

**Comment by DavideD** [comment]
CI is a bit weird right now, I will re-launch the checks in a bit

**Comment by DavideD** [comment]
Weird, GitHub wasn' t happy about the version of the gradle wrapper we were using.
I've updated it to he latest and it works now.

**Pull request merged**
