### PR TITLE
[#651] Update examples folders

### PR DESCRIPTION
**Pull request by DavideD**
I've moved them to:
```
examples/session-example
examples/native-sql-example
```
and renamed the packages to:
```
org.hibernate.example.session.reactive
org.hibernate.example.nativesql.reactive
```

### CODE REVIEW

**Comment by DavideD** [comment]
It seems I broke something during the rebase. I'm working on it

**Review by gavinking — APPROVED** [review]
LGTM, thank you!

**Comment by gavinking** [comment]
Wait: I don't see any changes to the Gradle build? Does the project really load correctly in IntelliJ? 'Cos that was what I had problems with.

**Comment by DavideD** [comment]
> Wait: I don't see any changes to the Gradle build? Does the project really load correctly in IntelliJ? 'Cos that was what I had problems with.

What do you mean? The changes are in the settings: https://github.com/hibernate/hibernate-reactive/pull/654/commits/3e1c22f5ddfd0487b935bc5970d4e58b794904e8

**Comment by gavinking** [comment]
Oh OK, I missed it. Fine.

**Comment by DavideD** [comment]
Should I rename the packages to:
```
org.hibernate.reactive.example.session
org.hibernate.reactive.example.nativesql
```
?

**Comment by gavinking** [comment]
> Should I rename the packages to:
> 
> ```
> org.hibernate.reactive.example.session
> org.hibernate.reactive.example.nativesql
> ```
> 
> ?

Fine by me.

**Pull request merged**
