### PR TITLE
workaround for collections in field-level lazy fetching

### PR DESCRIPTION
**Pull request by gavinking**
I feel like this must be a bug in Hibernate ORM that I'm dealing with here.

See discussion in #374.

### CODE REVIEW

**Comment by Sanne** [comment]
I'm a bit lost indeed, let me catch up..

**Comment by Sanne** [comment]
You won't need this fix anymore if we merge your proposal in ORM right?

**Comment by gavinking** [comment]
Aaahm.... it wouldn't be *necessary*, though I might still decide to merge it *anyway*. Need to think about that some more.

**Comment by gavinking** [comment]
Actually I'm going to merge this anyway. I can always rip out the stuff that sets the collection field if we turns out we ultimately don't need it.

**Pull request merged**
