### PR TITLE
Upgrade to Vert.x 4.1.4

### LINKED ISSUE #955: Upgrade Vert.x to 4.1.4
SchemaMigrator/SchemaValidator  "grouped" strategy will not work properly using DB2 or SQL Server  until the following issues are fixed:

For SQL Server: https://github.com/eclipse-vertx/vertx-sql-client/issues/1032 (fixed targeting 4.1.4)
Required by https://github.com/hibernate/hibernate-reactive/issues/912

For DB2: https://github.com/eclipse-vertx/vertx-sql-client/issues/1033
Required by https://github.com/hibernate/hibernate-reactive/issues/911

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #955

### CODE REVIEW

**Comment by DavideD** [comment]
@Sanne Quarkus seems to be still on 4.1.3, any particular reason?

**Comment by Sanne** [comment]
I'm not sure. I suspect the team didn't get to it yet as it was just released :) Let's give them a couple days to test?

But we could merge this if you need it quickly, since there are no code changes it should be easy to override the versions in Quarkus (in worse case); just be careful in tracking 4.1.4 specific funcionality in subsequent patches, in the remote case in which this would need to be reverted.

**Comment by DavideD** [comment]
I prefer to wait for quarkus. This version is needed for #911 and #912 but we haven't a pr yet

**Comment by gbadner** [comment]
Looks like https://github.com/eclipse-vertx/vertx-sql-client/issues/1033 didn't get fixed in 4.1.4, so DB2 "grouped" strategy will still be broken.

**Comment by DavideD** [comment]
> Looks like [eclipse-vertx/vertx-sql-client#1033](https://github.com/eclipse-vertx/vertx-sql-client/issues/1033) didn't get fixed in 4.1.4, so DB2 "grouped" strategy will still be broken.

That's ok for me. We can focus on MSSQL and we will fix Db2 when we can

**Review by Sanne — APPROVED** [review]
The Quarkus upgrade was merged: https://github.com/quarkusio/quarkus/pull/20308

**Pull request merged**
