### PR TITLE
test the exception type after a UK violation

### PR DESCRIPTION
**Pull request by gavinking**
See #465.

Apparently Mutiny *does* filter out the `CompletionException`s, which is *great*.

Is that right, @cescoffier?

### CODE REVIEW

**Comment by DavideD** [comment]
I think so, we test already exceptions for Mutiny and CompletionStage in different places and that's what happens

**Comment by gavinking** [comment]
> I think so, we test already exceptions for Mutiny and CompletionStage in different places and that's what happens

Yeah, but we didn't have any tests for a proper `PersistenceException`. At least not AFAICS.

**Review by DavideD — APPROVED** [review]
Looks good but don't we already have this test?

Mmh...probably not with `withTransaction`

**Comment by gavinking** [comment]
Oh, we did have one in `StageExceptionsTest` and `MutinyExceptionsTest`. But they don't actually test the thing I was most interested in.

**Comment by gavinking** [comment]
Anyway, might as well push these because in principle they are slightly different (they use `withTransaction()` so there are extra levels of wrapping).

**Comment by DavideD** [comment]
Yes, not complaining :-D

**Comment by cescoffier** [comment]
> Apparently Mutiny does filter out the CompletionExceptions, which is great.

Yes, we unwrap the "cause" when we see these.

**Comment by gavinking** [comment]
Great, perfect, thanks.

**Pull request merged**
