### PR TITLE
15 Support for HQL update queries

### PR DESCRIPTION
**Pull request by DavideD**
Built on top of https://github.com/hibernate/hibernate-reactive/pull/116

Add support for HQL update queries. I'm not sure if you prefer to have it as a separate  PR or if you want me to add the additional commits to the previous PR.

Let me know.

### CODE REVIEW

**Comment by gavinking** [comment]
@Davide looks great.

**Comment by gavinking** [comment]
@DavideD why don't you go ahead and merge this

**Comment by DavideD** [comment]
I was waiting for the ORM release

**Comment by gavinking** [comment]
Oh well I was thinking of temporarily making master depend on `5.5.0-SNAPSHOT` like we did once before.

But if you prefer we could also create an "integration" branch on the main repo to start integrating these various patches and finishing development of the first release.

**Comment by DavideD** [comment]
I don't think it's necessary for now, it is just that they will finish the release today. I don't mind to wait but if you are itching we can merge this now.

**Comment by DavideD** [comment]
I changed my mind, merged https://github.com/hibernate/hibernate-reactive/pull/119

**Comment by gavinking** [comment]
> I don't think it's necessary for now, it is just that they will finish the release toda

Ah that's good, I didn't realize.

**Pull request merged**
