### PR TITLE
block (hi/lo) id generation

### PR DESCRIPTION
**Pull request by gavinking**
For #47

### CODE REVIEW

**Comment by gavinking** [comment]
Anyone want to review this before I merge it?

**Comment by gavinking** [comment]
> Anyone want to review this before I merge it?

@Sanne?

**Comment by gavinking** [comment]
Hrm, some problem on MySQL.

**Comment by Sanne** [comment]
sorry I won't have time to do a proper review like this code probaly deserves, as it's quite critical to get the concurrency right.
(I'm on PTO from tomorrow for a week).

It might be worth adding an additional integration test which uses multiple threads, hammers your synchronization points and then verifies that all generated IDs are strictly unique? We have similar tests in both ORM and OGM, and have been very useful to nail some corner cases - including finding some bugs in NoSQL databases (!)

**Comment by Sanne** [comment]
P.S. I can start working on the multi-threaded tests, unless you'd like to implement them yourself..  just let me know your preference! Thanks

**Comment by gavinking** [comment]
>  I can start working on the multi-threaded tests

That would be _awesome_.

> unless you'd like to implement them yourself

Ummm, yeah, nah, not particularly :-)

**Comment by Sanne** [comment]
ok, I'll take care of the multithreaded tests - but I'll only be able to start next wednesday, I hope that's fine.

**Comment by gavinking** [comment]
> it's quite critical to get the concurrency right.

Yup, already found one concurrency bug (see the comments inline in the code).

**Comment by gavinking** [comment]
> Hrm, some problem on MySQL.

Fixed now.

**Comment by gavinking** [comment]
> I'll only be able to start next wednesday, I hope that's fine.

@Sanne are you still planning on working on this this week?

Because if not, my preference would be to just merge the work I've done so far, and add the tests later.

(Sure, there's certainly a risk of concurrency-related bugs but I feel like they should be fixable.)

**Comment by Sanne** [comment]
hi, yes I plan to work on this but starting Wednesday as I'm currently
away. Also it might take a while as other emails I've peeked at suggest
other priorities :(

Feel free to not consider my tests a blocker, I also prefer iterations.

**Comment by gavinking** [comment]
> Feel free to not consider my tests a blocker

I rebased, fixed some conflicts, and merged.

**Pull request merged**
