### PR TITLE
Drop extra Databases and update README 

### PR DESCRIPTION
**Pull request by DavideD**
A couple of missing bits for #754

### CODE REVIEW

**Comment by DavideD** [comment]
I don't think one needs additional permission to drop the database if they've created it.

**Comment by gavinking** [comment]
Great, thanks :-)

> I don't think one needs additional permission to drop the database if they've created it.

Nope, it seems not.

**Comment by gavinking** [comment]
Oops, what did I do?!

It didn't pass the CI build, and I didn't notice.

I *did* test it locally.

**Comment by gavinking** [comment]
Ugh, it broke the tests on Cockroach. I should definitely not have merged it. Sorry.

**Comment by DavideD** [comment]
Yeah, I noticed. No problem

**Pull request merged**
