### PR TITLE
schema export via reactive driver and fix for bug #113

### PR DESCRIPTION
**Pull request by gavinking**
This supersedes #112.

### CODE REVIEW

**Comment by gavinking** [comment]
Alright, folks, so shall I merge this one?

**Comment by gavinking** [comment]
Silence indicates consent.

**Comment by DavideD** [comment]
No, it doesn't

**Comment by DavideD** [comment]
Maybe if you put a deadline. Anyway, it looks good, feel free to merge it

**Comment by gavinking** [comment]
Pushed manually.

**Comment by aguibert** [comment]
This has broken CI because it depends on core 5.5.0-SNAPSHOT. I'll create a new PR that does a clone+build of core 5.5.0-SNAPSHOT so we can still have CI coverage until the next version of core is released.

Aside from that, it looks like the user has to do 2 things to enable this:
1) register the no-op connection provider
2) Set the custom generation target

Can we make it so these steps happen automatically and the user gets the RX-based schema creation out of the box?

**Comment by DavideD** [comment]
> This has broken CI because it depends on core 5.5.0-SNAPSHOT. I'll create a new PR that does a clone+build of core 5.5.0-SNAPSHOT so we can still have CI coverage until the next version of core is released.

The new ORM release will be ready shortly, before the end of the day. We decided to do an exception for this time and merge the PRs even if they refer to an unreleased version.
It's OK if you test it locally.

**Comment by gavinking** [comment]
> Can we make it so these steps happen automatically

Yes, I was already working on that, and I just pushed the result.

**Comment by gavinking** [comment]
> Yes, I was already working on that, and I just pushed the result.

Excuse me: I have pushed part 1 but not yet part 2.

**Comment by DavideD** [comment]
@gavinking Any idea about this error? https://github.com/hibernate/hibernate-reactive/pull/122/checks#step:4:151

**Comment by gavinking** [comment]
> @gavinking Any idea about this error? https://github.com/hibernate/hibernate-reactive/pull/122/checks#step:4:151

I imagine you're referring to the test failure I fixed [here](https://github.com/hibernate/hibernate-reactive/commit/4e8b51adc43dcc5251946205047ff9e6c8290e27).

**Comment by DavideD** [comment]
Yes, it's working now, thanks

**Pull request closed without merging**
