### PR TITLE
Vert.x updates

### PR DESCRIPTION
**Pull request by DavideD**
I've applied the commits from `main`.
I've also upgraded to `4.0.3` because I suspect it will work now.

### CODE REVIEW

**Comment by DavideD** [comment]
@blafond  could you check why this build fails?
And veritfy that it works locally. It needs to be tested on DB2.
Thanks

**Comment by blafond** [comment]
sure

**Comment by DavideD** [comment]
Did you use this?
```
./gradlew build -Pdb=DB2 -Pdocker -PvertxVersion='[4,5)'
```

**Comment by blafond** [comment]
no.. but just did

```
> Task :hibernate-reactive-core:compileJava FAILED
/home/blafond/Development/hibernate/hibernate-reactive/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:197: error: incompatible types: bad type in conditional expression
                return transaction != null ? transaction : connection;
                                             ^
    Transaction cannot be converted to SqlClient
/home/blafond/Development/hibernate/hibernate-reactive/hibernate-reactive-core/src/main/java/org/hibernate/reactive/pool/impl/SqlClientConnection.java:202: error: incompatible types: Future<Transaction> cannot be converted to Transaction
                transaction = connection.begin();

```

**Comment by DavideD** [comment]
Make sure to use the right branch. This PR is for `vert.x-4`

**Comment by DavideD** [comment]
It seems I can replicate the issue locally

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/688

**Pull request closed without merging**
