### PR TITLE
Support @ValueGenerationType

### PR DESCRIPTION
**Pull request by geoand**
Fixes: GeneratedProperty*Test (with this change, the failures drop to 138 from 141)

~~Requires a Hibernate ORM patch. I have currently made [these](https://github.com/geoand/hibernate-orm/commit/0bd17320465959924b28bf3d9fc8e4cc8afc8dcd) changes against `6.2.0.CR2` and not the `6.2` branch because that branch has moved and HR needs to be updated to compile~~

### CODE REVIEW

**Comment by gavinking** [comment]
Awesome.

**Comment by geoand** [comment]
❤️

**Comment by DavideD** [comment]
@geoand Can you send the PR for ORM with the changes required for this PR, please?

**Comment by geoand** [comment]
Sure. Against which branch?

**Comment by DavideD** [comment]
Should be `main`

**Comment by geoand** [comment]
Great, I'll take care of it over the weekend

**Comment by geoand** [comment]
PR opened

**Comment by geoand** [comment]
The branch before this PR has `130` failing tests and with this the numbers drops to `127`

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/1462
Thanks

**Comment by geoand** [comment]
🎉

**Pull request merged**
