### PR TITLE
Vert.x 4 updates

### PR DESCRIPTION
**Pull request by DavideD**

### CODE REVIEW

**Comment by gavinking** [comment]
Does anyone think we should de a beta release of HR for vert.x 4?

**Comment by DavideD** [comment]
I suppose we could. 
I would require a change in the artifact or groupid though.

Is there a plan about using Vert.x 4 in Quarkus?

**Comment by gavinking** [comment]
> Is there a plan about using Vert.x 4 in Quarkus?

Well, yes, but the whole conversation has all got a bit confusing due to the debate about `jakarta.`.

**Comment by gavinking** [comment]
> It will require a change in the artifact or group id.

Hrm. I suppose you're right. Well, is there any reason to not create a `hibernate-reactive-core-vertx4` artifact id?

**Comment by DavideD** [comment]
None that I can think of. It was merely an observation.

**Pull request merged**
