### PR TITLE
[#282] Throw LazyInitializationException

### PR DESCRIPTION
**Pull request by DavideD**
https://github.com/hibernate/hibernate-reactive/issues/282

### CODE REVIEW

**Comment by gavinking** [comment]
I suppose that's OK. It doesn't feel like the ideal place to do this, but if there's nowhere else we can reasonably do it, it's fine I guess.

**Comment by DavideD** [comment]
Thinking about it more,  I'm not even sure this is a LazyInitializationException. This is not related to the session being closed prematurely.

**Comment by DavideD** [comment]
Well, I suppose it is good enough for now

Merged https://github.com/hibernate/hibernate-reactive/pull/286

**Comment by gavinking** [comment]
Well I do think it's legitimately a `LazyInitializationException`, which has the semantics of "we can't fetch this unfetched association for you right now", even if the reason we can't fetch it is a little different.

**Comment by DavideD** [comment]
I agree, it's just that the javadoc for LazyInitializationException is quite specific.

**Pull request merged**
