### PR TITLE
Remove layout property for logs

### PR DESCRIPTION
**Pull request by DavideD**
It is not user friendly for people with some type of colour blindness.

Please, let's try to avoid changing the default colours in the project. It's very personal and everybody is more than capable of customising the working environment if needed

### CODE REVIEW

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/372

**Comment by gavinking** [comment]
Huh????

So IntelliJ and Eclipse shouldn't do syntax highlighting by default?

I'm sick to death of not being able to read the SQL in the Hibernate logs because there's no syntax highlighting. And it's amazing to me that in 20 years we did nothing about that, and made ourselves and our users suffer.

> It is not user friendly for people with some type of colour blindness.

And that's perfectly fine, because people with accessibility needs are quite accustomed to having to make their own adjustments. Just like I have to increase the font size on my phone.

> It's very personal and everybody is more than capable of customising the working environment if needed

So if it's so easy to customize, what's the problem with having a default?

**Comment by DavideD** [comment]
> So if it's so easy to customize, what's the problem with having a default?

I don't want to do it right now.
I can read pretty well the default log but the colour scheme you picked makes it hard for me to look at the log.
Also, the colour scheme of my ide is configured to work with a default log, if you start to add colours to it I need to start figuring out how to make the two works.

> I'm sick to death of not being able to read the SQL in the Hibernate logs because there's no syntax highlighting. And it's amazing to me that in 20 years we did nothing about that, and made ourselves and our users suffer.

???
The pattern you picked only highlight the priority and the Class name, doesn't do anything for the SQL.
We can probably achieve the same effect without dealing with colours and using chars to separate them.
But if you really want to use colours, at least let's try to find some other combination.

**Comment by gavinking** [comment]
So you haven't actually followed any of what I was working on the last few days, have you?

You just decided to arbitrarily roll back changes I made after quite a lot of thinking and experimentation.

**Comment by gavinking** [comment]
(Run `MutinyMain` and you'll see why I wanted the log categories colorized.)

**Comment by DavideD** [comment]
I didn't merge the PR.
I didn't touch the example.

[The PR that you sent](https://github.com/hibernate/hibernate-reactive/pull/366) has only one commit saying:`upgrade to log4j 2`. I wouldn't expect to also change the colour scheme and among all the changes is something that could have been easily missed.
I also don't see the changes for the example in that PR. 

I still think some of the colours need to change

**Comment by DavideD** [comment]
But yes, I guess I shouldn't have merged the PR and have a better look at the commits.
I wasn't working on the SQL on the console and didn't realise the ultimate goal of that specific change in the core project.

**Comment by DavideD** [comment]
> I also don't see the changes for the example in that PR.

Sorry, I was wrong about it. The commit also contains the changes for the example.

**Comment by DavideD** [comment]
You know what, nevermind, I'm going to revert my changes.

**Comment by DavideD** [comment]
> You know what, nevermind, I'm going to revert my changes.
Done

**Pull request merged**
