### PR TITLE
Upgrade to Hibernate ORM 5.6.2.Final

### PR DESCRIPTION
**Pull request by Sanne**
- https://in.relation.to/2021/12/08/hibernate-orm-562/

### CODE REVIEW

**Comment by Sanne** [comment]
ouch looks like I underestimated this

**Comment by DavideD** [comment]
What happened? Last minute change?

**Comment by Sanne** [comment]
no?

**Comment by DavideD** [comment]
Not that it matters at this point but I'm asking because the build that test with the snapshot was working up to a couple of hours a ago: https://github.com/hibernate/hibernate-reactive/actions

But then failed an hour ago

**Comment by Sanne** [comment]
Snapshots are unreliable - these changes have been there for some days

**Comment by DavideD** [comment]
Do you want me to have a look at it or are you taking care of this?

**Comment by Sanne** [comment]
If you could have a look that's great. I won't be able to look today.

I suspect this is the cause:
 - https://github.com/hibernate/hibernate-orm/pull/4351

**Comment by DavideD** [comment]
I will try to have a look at it later in the day

**Comment by DavideD** [comment]
Superseeded by https://github.com/hibernate/hibernate-reactive/pull/1079

**Pull request closed without merging**
