### PR TITLE
[#901] removed failing assertion

### PR DESCRIPTION
**Pull request by blafond**
Fixes [#901](https://github.com/hibernate/hibernate-reactive/issues/901)

### CODE REVIEW

**Comment by DavideD** [comment]
I have this exception on my machine:
```
Not equals : Z != +01:00
java.lang.AssertionError: Not equals : Z != +01:00
	at io.vertx.ext.unit.impl.TestContextImpl.reportAssertionError(TestContextImpl.java:362)
	at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:258)
	at io.vertx.ext.unit.impl.TestContextImpl.assertEquals(TestContextImpl.java:245)
	at org.hibernate.reactive.UTCTest.lambda$testOffsetDateTime$5(UTCTest.java:122)
```

**Comment by blafond** [comment]
I changed my laptop time zone to different values and it does fail only on BTC (i.e. Z)

Fails in `ZoneOffset.equals()` on this check:  `return this.totalSeconds == ((ZoneOffset)obj).totalSeconds;`
where `this.totalSeconds` is **0** and `((ZoneOffset)obj).totalSeconds` is **3600**

**Comment by DavideD** [comment]
As usual, dealing with dates is a pain. Honestly, I don't have a solution at the moment.
I'm fine with just removing the assertion for now.

**Comment by blafond** [comment]
I removed the first assertion in that test.  The complexity of time zone rules seems to prevent a reasonable/working check on zone offset.

**Pull request merged**
