### PR TITLE
[#545] Replace Quarkus version with links to the quickstarts

### PR DESCRIPTION
**Pull request by DavideD**

### CODE REVIEW

**Comment by DavideD** [comment]
@gavinking is this OK?

**Comment by DavideD** [comment]
Maybe I shouldn't mention the quickstarts in the compatibility section and actually add the link in the Example section

**Comment by gavinking** [comment]
yeah "compatibility" seems like a strange place to put it.

**Comment by DavideD** [comment]
I've changed it

**Comment by DavideD** [comment]
Merged.

**Pull request merged**
