### PR TITLE
Update reference documentation style sheet

### LINKED ISSUE #1882: Clean up Hibernate Reactive documentation page
Google code prettify is not maintained any more and the link to the CSS causes a CSP error when loading the documentation page.

We also need to add the Hibernate logo at the beginning of the docs like in the other projects.

See https://github.com/hibernate/hibernate-reactive/pull/1874

### PR DESCRIPTION
**Pull request by DavideD**
Fix #1882:
* Replace `prettify` with `rouge` (solve the CSP issue with prettify.css)
* Add Hibernate logo on top of the documentation page
* Apply some changes to the default CS

I've updated [staging.hibernate.org](https://staging.hibernate.org/reactive/documentation/2.3/reference/html_single/) with the new CSS. It seems close enough to the one used by prettify.

/cc @marko-bekhta

### CODE REVIEW

**Comment by marko-bekhta** [comment]
image
hmm 🙈 maybe you need to explicitly specify the highlighter in the gradle task ?

**Comment by DavideD** [comment]
>  hmm 🙈 maybe you need to explicitly specify the highlighter in the gradle task ?

Yes, specifying the highlighter is helpful  :smiley_cat: 
Sorry, I did a last minute change and forgot to update the file.
Should be fixed now.

**Comment by gavinking** [comment]
LGTM, thanks @DavideD

**Comment by DavideD** [comment]
Merged, thanks.
The documentation in production will be updated after the next release.

**Pull request merged**
