### PR TITLE
Close session in case of exception in 

### LINKED ISSUE #811: withSession doesn't close the session in case of exception
@gavinking shouldn't we close the session if an exception occurs?

Example:
```
	@Test
	public void testExceptionInWithSession(TestContext context) {
		final Stage.Session[] savedSession = new Stage.Session[1];
		test( context, getSessionFactory().withSession( session -> {
			context.assertTrue( session.isOpen() );
			savedSession[0] = session;
			throw new RuntimeException( "No Panic: This is just a test" );
		} ).handle( (o, t) -> context.assertFalse( savedSession[0].isOpen(), "Session should be closed" ) ) );
	}
```

### PR DESCRIPTION
**Pull request by DavideD**
Follows #813 
Fixes #811 

Hopefully, this will look a bit better.

### CODE REVIEW

**Review by gavinking — APPROVED** [review]
This looks fine to me now, thanks.

The only thing I'm thinking is that we should add back some sort of `Closeable` interface, like we had before, in order to avoid having to pass around method refs.

But I can do that as a separate task if you prefer.

**Comment by gavinking** [comment]
Wait, @DavideD I think you missed a similar change to `newStatelessSession()` for Mutiny.

**Comment by DavideD** [comment]
> The only thing I'm thinking is that we should add back some sort of `Closeable` interface, like we had before, in order to avoid having to pass around method refs.

Definitely, I was going to propose it :-)
Yes, please,  have a look at it as a separate issue.

**Comment by DavideD** [comment]
> Wait, @DavideD I think you missed a similar change to `newStatelessSession()` for Mutiny.

Good catch, I've probably lost the change during a rebase

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/814

Thanks

**Pull request merged**
