### PR TITLE
fix doc for getSingleResult() and add getSingleResultOrNull()

### PR DESCRIPTION
**Pull request by gavinking**
Proposed `Query.getSingleResultOrNull()` method.

### CODE REVIEW

**Comment by gavinking** [comment]
Apparently I forgot the semantics of `getSingleResult()` :-)

**Comment by gavinking** [comment]
Feedback on this change?

**Comment by DavideD** [comment]
Looks good to me.
Shouldn't also test that we throw the expected exceptions?

**Comment by DavideD** [comment]
> Apparently I forgot the semantics of getSingleResult() :-)

So I'm not the only one :)
I had the same reaction with ORM not so long ago

**Comment by gavinking** [comment]
> So I'm not the only one :)

It's easily forgettable, since it's different to the semantics of `find()`.

**Pull request merged**
