### PR TITLE
[Draft] to fix "java.lang.IllegalStateException: Session/EntityManager is closed"

### PR DESCRIPTION
**Pull request by Sanne**
Relates to https://github.com/quarkusio/quarkus/issues/22433 and #1073

@DavideD

### CODE REVIEW

**Comment by gavinking** [comment]
Oh, right, fine, this undoes the thing I just noticed.

I think we should definitely merge this. If i understand correctly, the change made in https://github.com/hibernate/hibernate-reactive/pull/948/files would cause the Hibernate session and transaction between _all_ threads in a verticle. If that's right, then no wonder users were running into concurrency problems.

**Comment by DavideD** [comment]
@gavinking, Please, check with us before merging things there are in draft
and assign to somebody else

**Comment by gavinking** [comment]
Um. No, I don't think that's a reasonable thing to yell at me about. The change to use `put()` and `get()` instead of `putLocal()` and `getLocal()` was _clearly wrong_, and certainly unintended. I know because this is code I originally wrote and I know what it's supposed to do.

And the change that broke it broke Hibernate Reactive _for essentially every user_. It's _extremely_ embarrassing that we have not noticed this issue since September, and have had multiple users report multiple bugs that I assume stem from this, and we have not done anything about it until now.

So, yeah, my fault for being swapped out, for sure, but right now we need to prioritize the fuck out of getting this fix out into a release, not keep sitting around fiddling and twiddling our fingers and worrying what process is followed when merging fixes to serious bugs!

**Comment by gavinking** [comment]
Seriously, we should have been on top of this *way earlier* and we weren't.

We need to be feeling quite bad about this right now.

**Comment by Sanne** [comment]
> We need to be feeling quite bad about this right now.

Don't worry, I felt quite bad when I realized my mistake.

But there's no reason to rush things as we won't be able to release until tomorrow the earliest.

**Pull request merged**
