### PR TITLE
change voidlike methods to CompletionStage<Void>

### LINKED ISSUE #347: return CompletionStage<Void> instead of CompletionStage<Session> from voidlike session methods
Currently operations like `remove()` return `CompletionStage<Session>` or `Uni<Session>`, but I'm now inclined to think that this is useless given the idioms we have for obtaining a reference to the `Session`, and I'm considering changing the return types to `CompletionStage<Void>` and `Uni<Void>`.

Any objections?

### PR DESCRIPTION
**Pull request by gavinking**
It's not useful to have them return `CompletionStage<Session>` and indeed it encourages bad code.

Fixes #347

### CODE REVIEW

**Comment by DavideD** [comment]
Rebased and merged https://github.com/hibernate/hibernate-reactive/pull/349

THanks!

**Comment by DavideD** [comment]
Sorry, closed the wrong one

**Comment by DavideD** [comment]
@gavinking 
Because I've merged https://github.com/hibernate/hibernate-reactive/pull/346 there are now some conflicts. Could you rebase it and then merge it, please? It's just a couple of tests that have changed.

Because this is a big one I will wait to merge other PRs until it's included as to avoid additional conflicts.

**Comment by gavinking** [comment]
Yep I knew there would be conflicts (in tests).

**Comment by gavinking** [comment]
Fixed.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/349

Thanks
It's nice that we can now avoid this:
```
.map( v-> this );
```

**Comment by gavinking** [comment]
> It's nice that we can now avoid this:

Yup. I thought that too.

**Pull request closed without merging**
