### PR TITLE
Update podman file and Change password

### PR DESCRIPTION
**Pull request by DavideD**
#130 Update the podman configuration
#134 Change username, password and database for tests

### CODE REVIEW

**Comment by gavinking** [comment]
@DavideD the database usernames are in other places too: in the test suite, and in the README, for example.

**Comment by DavideD** [comment]
Thanks @gavinking, it should be fixed now

**Comment by DavideD** [comment]
We still need to add a section in the README about creating the db in DB2

**Comment by DavideD** [comment]
I'm going to merge this since there are no other PR at the moment. Remember that it changes the credentials if you are not using the docker profile. Thanks

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/135
Thanks

**Pull request closed without merging**
