### PR TITLE
Infinite recursion calls

### LINKED ISSUE #775: Infinite recursion calls in ReactiveBatchingEntityLoader#load
See https://github.com/hibernate/hibernate-reactive/blob/c91dd01e7a1d779c270b08f411606c2d5f1dd3f6/hibernate-reactive-core/src/main/java/org/hibernate/reactive/loader/entity/impl/ReactiveBatchingEntityLoader.java#L57

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #775

Any idea how to test this?

### CODE REVIEW

**Comment by gavinking** [comment]
Well, where precisely is the infinte recursion? I don't see it.

There was none at `ReactiveBatchingEntityLoader.load()` because that method is overridden on both concrete subclasses. (Nevertheless it's better to delete it.)

The motivation for the other change I'm not seeing, so that must be causing the recursion, though it's not obvious how.

**Comment by DavideD** [comment]
> Well, where precisely is the infinte recursion? I don't see it.

I should have said **potential** Infinite recursion.

As you said, all the classes override the method so we never experience it.

The other change is unrelated, it removes a deprecated method call.

**Comment by DavideD** [comment]
> I should have said potential Infinite recursion.

Well... unless you consider causing a stackoverflow exception a good default implementation :-)

**Comment by DavideD** [comment]
Merged, thanks

**Comment by gavinking** [comment]
> Well... unless you consider causing a stackoverflow exception a good default implementation :-)

It's not ideal :-)

**Pull request merged**
