### PR TITLE
Added tests for @SqlInsert, @SqlUpdate, and @SqlDelete containing stored procedures  

### PR DESCRIPTION
**Pull request by DavideD**
@blafond 

I've changed a bit your PR:
* Fixed the name of the test class
* Reformatted the code
* Removed the `@NamedStoreProcedure`, it's not needed for these tests (I think)

Can you merge this if you agree with the changes?

Thanks

### CODE REVIEW

**Comment by DavideD** [comment]
Fixes #592

**Comment by gavinking** [comment]
All LGTM.

The point is that we've proved that stored procedures work in HR, and if we ever need to remember how to do them, this is here to remind us.

**Comment by blafond** [comment]
This verifies the concept against a PG instance

**Comment by DavideD** [comment]
Thanks

**Pull request merged**
