### PR TITLE
697,698 : Create workflow for testing the latest Vert.x SQL client snapshots and re-enable DB2 tests

### PR DESCRIPTION
**Pull request by gbadner**
https://github.com/hibernate/hibernate-reactive/issues/698

https://github.com/hibernate/hibernate-reactive/issues/697

### CODE REVIEW

**Comment by gbadner** [comment]
@tsegismont, I've created this branch off of main and cherry-picked your [commit](https://github.com/hibernate/hibernate-reactive/pull/741/commits/2f0e2b237ba2d4baf71aacbd4744d21c8c188cb9). Unfortunately, something seems out of sync, because `NaturalIdTest` is failing with this command:

`./gradlew clean test --tests "org.hibernate.reactive.NaturalIdTest" -PenableSonatypeOpenSourceSnapshotsRep -PvertxVersion=4.1.0-SNAPSHOT`

`[2021-04-30 15:45:34] SEVERE io.vertx.core.impl.ContextImpl                          Unhandled exception
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: io/vertx/core/net/impl/clientconnection/ConnectResult
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1.connect(SqlConnectionPool.java:96)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.connect(SimpleConnectionPool.java:240)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool$Acquire.lambda$execute$2(SimpleConnectionPool.java:526)
	at io.vertx.core.net.impl.pool.CombinerExecutor.pollAndExecute(CombinerExecutor.java:55)
	at io.vertx.core.net.impl.pool.CombinerExecutor.submit(CombinerExecutor.java:43)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.execute(SimpleConnectionPool.java:231)
	at io.vertx.core.net.impl.pool.SimpleConnectionPool.acquire(SimpleConnectionPool.java:555)
	at io.vertx.sqlclient.impl.pool.SqlConnectionPool.acquire(SqlConnectionPool.java:192)
	at io.vertx.sqlclient.impl.PoolBase.acquire(PoolBase.java:165)
	at io.vertx.sqlclient.impl.PoolBase.getConnection(PoolBase.java:132)
	at io.vertx.sqlclient.impl.PoolBase.getConnection(PoolBase.java:116)
	at org.hibernate.reactive.pool.impl.SqlClientPool.lambda$getConnectionFromPool$1(SqlClientPool.java:76)
	at org.hibernate.reactive.pool.impl.Handlers.toCompletionStage(Handlers.java:24)
	at org.hibernate.reactive.pool.impl.SqlClientPool.getConnectionFromPool(SqlClientPool.java:75)
	at org.hibernate.reactive.pool.impl.SqlClientPool.getConnection(SqlClientPool.java:66)
	at org.hibernate.reactive.provider.service.ReactiveGenerationTarget.lambda$release$1(ReactiveGenerationTarget.java:69)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/vertx/core/net/impl/clientconnection/ConnectResult
	... 26 more
Caused by: java.lang.ClassNotFoundException: io.vertx.core.net.impl.clientconnection.ConnectResult
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 26 more

[2021-04-30 15:50:33] WARNING io.vertx.core.impl.BlockedThreadChecker                 Thread Thread[vert.x-worker-thread-0,5,main] has been blocked for 299920 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.hibernate.reactive.provider.service.ReactiveGenerationTarget.release(ReactiveGenerationTarget.java:81)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:131)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:112)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:145)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:318)
	at org.hibernate.reactive.session.impl.ReactiveSessionFactoryImpl.<init>(ReactiveSessionFactoryImpl.java:33)
	at org.hibernate.reactive.provider.service.ReactiveSessionFactoryBuilder.build(ReactiveSessionFactoryBuilder.java:52)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:708)
	at org.hibernate.reactive.BaseReactiveTest.createHibernateSessionFactory(BaseReactiveTest.java:192)
	at org.hibernate.reactive.BaseReactiveTest.lambda$startFactoryManager$8(BaseReactiveTest.java:176)
	at org.hibernate.reactive.BaseReactiveTest$$Lambda$32/1428163560.get(Unknown Source)
	at org.hibernate.reactive.testing.SessionFactoryManager.start(SessionFactoryManager.java:31)
	at org.hibernate.reactive.BaseReactiveTest.startFactoryManager(BaseReactiveTest.java:176)
	at org.hibernate.reactive.BaseReactiveTest$$Lambda$28/77571448.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:160)
	at io.vertx.core.impl.ContextImpl$$Lambda$31/1608016024.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:158)
	at io.vertx.core.impl.ContextImpl$$Lambda$30/345268207.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$20/1083627375.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
`

**Comment by gbadner** [comment]
@tsegismont, also, the test ran for 5 minutes before finally timing out.

**Comment by tsegismont** [comment]
@gbadner can you start the build again? I believe this was due to changes in Vert.x core not yet published in snapshots repo.

**Comment by gbadner** [comment]
@tsegismont, thanks, it works now! There are no failures using PosgreSQL. I'll go ahead and create the workflow and see how the other dialects do.

**Comment by gbadner** [comment]
@gavinking, I'd like to run tests with SQL Server using Vert.x 4.1.0-SNAPSHOT. Are there details for doing this with podman?

**Comment by gavinking** [comment]
@gbadner I have never tried. I think @DavideD knows. And @tsegismont.

**Comment by DavideD** [comment]
I've rebased my initial branch here:
https://github.com/DavideD/hibernate-reactive/tree/mssql-server-main

Anyway, this is how you start sql server:
https://github.com/DavideD/hibernate-reactive/blob/mssql-server-main/podman.md#microsoft-sql-server

**Comment by DavideD** [comment]
Username is 'sa'.

You can check here the different properties you can set:
https://hub.docker.com/_/microsoft-mssql-server

**Comment by DavideD** [comment]
My branch doesn't contain Thomas changes.

**Comment by DavideD** [comment]
If everything is setup correctly, you should be able to test sql server
with:

```
. /gradlew testDbSqlserver -PvertxVersion='4. 1.0-SNAPSHOT'
```

**Comment by gbadner** [comment]
@DavideD, snapshots need to be enabled, so this needs to be added: `-PenableSonatypeOpenSourceSnapshotsRep`

Full command should be:

`./gradlew testDbSqlserver -PenableSonatypeOpenSourceSnapshotsRep -PvertxVersion=4.1.0-SNAPSHOT`

**Comment by tsegismont** [comment]
@gbadner I shared my changes in a PR to the branch of @DavideD : https://github.com/DavideD/hibernate-reactive/pull/13

**Comment by gbadner** [comment]
@tsegismont, I'm having some trouble cherry-picking commits from your branch. I'm working on a more recent branch off of main. I'm seeing conflicts, and I'm not sure how to resolve them.

I see now that you are actively working on supporting SQL Server using Vert.x 4.1.0-SNAPSHOT. I think for now, it would be best if I continue with this task without including SQL Server. I'll sync up with your work later.

**Comment by gbadner** [comment]
All tests pass using Vert.x 4.0.4-SNAPSHOT and 4.1.0-SNAPSHOT.

**Comment by gbadner** [comment]
The re-enabled DB2 tests pass using both Vert.x 4.0.4-SNAPSHOT and 4.1.0-SNAPSHOT.

The 3 jobs that fail were expected to fail because they use Vert.x 4.0.3.

**Comment by gbadner** [comment]
@DavideD, I forgot that there would be those failures when I added https://github.com/hibernate/hibernate-reactive/issues/697. Should I remove that commit here? I suppose the Vert.x version will ultimately be changed to 4.1.0, and the DB2 tests can be re-enabled at that time.

Also, when you mentioned that I should "add it it to the build on CI", will that happen automatically when this PR gets merged?

**Comment by DavideD** [comment]
> @DavideD, I forgot that there would be those failures when I added #697. Should I remove that commit here?

Yes, please. We cannot merge it at the moment and I don't think it's worth it to add extra logic to enable/disable them during the build.

> Also, when you mentioned that I should "add it it to the build on CI", will that happen automatically when this PR gets merged?

Yes, the workflow files you have updated define the behaviour on CI

**Comment by gbadner** [comment]
Removed the commit that enabled DB2 test and force-pushed.

**Comment by DavideD** [comment]
Thanks @gbadner, this looks great. I will just wait for the checks to pass and then I will merge it

**Pull request merged**
