### PR TITLE
Test against JDK 18 EA

### PR DESCRIPTION
**Pull request by yrodiere**

### CODE REVIEW

**Comment by yrodiere** [comment]
It seems this is failing because AdoptOpenJDK doesn't have a JDK 18 build yet: https://api.adoptopenjdk.net/v3/info/available_releases

Let's wait a bit more...

**Comment by Sanne** [comment]
re-running

**Comment by yrodiere** [comment]
Still no OpenJDK 18 in AdoptOpenJDK: https://api.adoptopenjdk.net/v3/info/available_releases

**Comment by Sanne** [comment]
triggering again, as I don't know how to interpret the response from https://api.adoptopenjdk.net/v3/info/available_releases

**Comment by yrodiere** [comment]
I'm giving up on waiting for AdoptOpenJDK/Adoptium to release their own JDK18 binaries; I changed a few things so that we download JDK18 automatically.

This means we will have to maintain the download URL up-to-date in the GitHub Actions workflow. On top of maintaining it up-to-date in Jenkins for all of our other projects... Hopefully one day we'll move everything in one place.

**Comment by DavideD** [comment]
Merged, thanks

**Pull request merged**
