### PR TITLE
[#287] Upgrade to vert.x-sql-client 3.9.2

### PR DESCRIPTION
**Pull request by DavideD**
Any reason to wait before including this update?

### CODE REVIEW

**Comment by DavideD** [comment]
There is a test failure, I will check

**Comment by gavinking** [comment]
> Any reason to wait before including this update?

Not as far as I know.

**Comment by Sanne** [comment]
I'd love to upgrade this ASAP, but I think we'd need to make sure Quarkus won't delay the matching upgrade.

**Comment by Sanne** [comment]
@gsmet / @FroMage / @aguibert  WDYT, can we be optimistic about this upgrade to happen soon in Quarkus?

**Comment by gsmet** [comment]
Funny thing, it was supposed to already be done here: https://github.com/quarkusio/quarkus/pull/10779 but... the BOM wasn't updated.

I pinged Clément. It's definitely something that should land soon in master.

**Comment by Sanne** [comment]
great, thanks @gsmet for the pointer. I see Clement's PR actually had the upgrade, maybe we lost some changes during the BOM moves?

**Comment by Sanne** [comment]
ah, no my bad. The `application/pom.xml` is missing it, Clement had it patched in `build-parent/pom.xml ` .. not sure why this property is duplicated.

**Comment by gsmet** [comment]
That's what I was saying in my message :). Clément is working on it, I pinged him a few minutes ago.

The property is duplicated because properties are not inherited from the bom and the one in build-parent is probably used in the doc. I had plans to create a `quarkus-properties` or `quarkus-versions` parent that could served as a common parent but never got to it. I would need to check with Alexey if it's a good idea anyway.

**Comment by gsmet** [comment]
@Sanne the Vert.x 3.9.2 upgrade has been merged to Quarkus master.

**Comment by Sanne** [comment]
awesome, thanks @gsmet !

**Pull request closed without merging**
