### PR TITLE
Upgrade to 5.4.31.Final and fix compatibility with ORM 5.5

### LINKED ISSUE #646: Re-enable workflow for 5.5 ORM SNAPSHOT
I've currently disabled the workflow for 5.5 as it was causing too many errors and I don't think it's fixable without
reverting a change in ORM 5.5 or a new release of ORM 5.4.

After talking to @Sanne about this, I'm not even sure if we need to continue tracking it.
I've created this issue as a reminder and in case somebody has a simple solution for making it works.

### PR DESCRIPTION
**Pull request by DavideD**
This is a draft because we need to upgrade to the next ORM 5.4 release before we can merge it.

Fixes #646

### CODE REVIEW

**Comment by gavinking** [comment]
This is cleaner anyway.

**Comment by Sanne** [comment]
force-pushed to trigger the CI jobs again

**Comment by Sanne** [comment]
Looks like we have some timeouts on DB2

**Comment by DavideD** [comment]
Yeah, I'm checking if I can find some workaround :-/

**Comment by DavideD** [comment]
@Sanne it seems to work now

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/724

**Pull request merged**
