### PR TITLE
New internal "Pool of pools" and disposal

### LINKED ISSUE #481: don't share `Pool`s between vert.x contexts in vert.x 3
According to @vietj, we're supposed to have a single connection `Pool` per vert.x context.

(At least that's my interpretation of what he told us.)

Note that this model is changing in vert.x 4, so this is a bug that only affects us on vert.x 3.

### PR DESCRIPTION
**Pull request by Sanne**
I have not tested it yet properly, and still need to figure out how Quarkus will be able to integrate this.

Fixes #481

### CODE REVIEW

**Comment by johnaohara** [comment]
@Sanne have you looked at how Agroal manages connections?

**Comment by Sanne** [comment]
hi @johnaohara !

No I couldn't get to that yet. In this case I'm not working on performance improvement but trying to figure out how to solve some integration issues - this relates to #481 and #475 - quite critical.

**Comment by johnaohara** [comment]
@Sanne np, the solution here looks very similar to how agroal caches connections in Threadlocals, but is trying to solve a different issue. I thought it could have been useful, but ignore me if not :)

**Review by DavideD — APPROVED** [review]
LGTM

**Comment by DavideD** [comment]
There are some problems with the examples. I'm checking

**Comment by Sanne** [comment]
Closing as this depends on #493 - and I want to do some adjustments after that is merged.

**Comment by Sanne** [comment]
Replaced by PR #500

**Pull request closed without merging**
