### PR TITLE
use static methods for more robust exception handling

### PR DESCRIPTION
**Pull request by gavinking**
I've tried to clean up the `handle()` methods a bit.

I also ran across some exception-handling stuff that can't possibly be right and fixed it.

### CODE REVIEW

**Comment by gavinking** [comment]
Something seems to be wrong with the CI.

**Comment by DavideD** [comment]
CI is back to normal now

**Comment by gavinking** [comment]
Well it still seems to fail with a lot of:

```
 org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:322)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302)
        at org.hibernate.reactive.containers.PostgreSQLDatabase.getJdbcUrl(PostgreSQLDatabase.java:31)
```

**Comment by DavideD** [comment]
RIght, it seems it's havin g problems downloading the docker images: 
```
        Caused by:
        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageNameFuture=java.util.concurrent.CompletableFuture@70d9b885[Completed normally], imagePullPolicy=DefaultPullPolicy(), dockerClient=LazyDockerClient.INSTANCE)
            at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1265)
            at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:600)
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:311)
            ... 5 more

            Caused by:
            com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://quay.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"}
                at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
                at org.testcontainers.dockerclient.transport.okhttp.OkHttpInvocationBuilder.lambda$executeAndStream$3(OkHttpInvocationBuilder.java:303)
                at java.lang.Thread.run(Thread.java:748)
```

**Comment by DavideD** [comment]
Rebased and merged https://github.com/hibernate/hibernate-reactive/pull/212

Thanks

**Pull request closed without merging**
