### PR TITLE
multi-table HQL update+delete

### PR DESCRIPTION
**Pull request by gavinking**
~~Limitations of initial implementation:~~

- ~~does not yet support parameters~~
- ~~does not properly support DB2~~

For #237

### CODE REVIEW

**Comment by gavinking** [comment]
@aguibert I ran into some ugly-lookin' errors when I tried to `create` or `declare` a temporary table on DB2. I suspect, but do not know for sure, that this is because the DB2 client doesn't support them yet. Is that right?

**Comment by aguibert** [comment]
@gavinking I haven't tested them specifically, but I would have assumed they work since regular table create statements work. Can you post an example of the SQL you're using to create/declare the temp table and I'll investigate?

**Comment by gavinking** [comment]
> Can you post an example of the SQL you're using to create/declare the temp table and I'll investigate?

Something like `declare global temporary table foo(id int)`

**Comment by gavinking** [comment]
I've added support for parameters, but I need https://github.com/hibernate/hibernate-orm/pull/3507.

**Comment by aguibert** [comment]
Created https://github.com/eclipse-vertx/vertx-sql-client/issues/747 over in vertx-sql-client to track this

**Comment by gavinking** [comment]
Cheers.

**Comment by gavinking** [comment]
Alright, so this work is good to go, once we get a new release of ORM.

**Comment by gavinking** [comment]
@Sanne I would really like to merge this big PR, but I need:

1) This pull request to be merged: https://github.com/hibernate/hibernate-orm/pull/3511
2) A release of core.

**Pull request merged**
