### PR TITLE
Disable use of Nationalized chars for MariaDb

### PR DESCRIPTION
**Pull request by DavideD**
@gavinking Is this is correct or there is something I'm missing?

### CODE REVIEW

**Comment by gavinking** [comment]
That seems pretty weird. Why do we need to disable the test especially for Maria?

**Comment by DavideD** [comment]
Otherwise it fails

**Comment by gavinking** [comment]
Yeah well I guessed that, but *why*?

**Comment by DavideD** [comment]
I'm going to merge this because it fixes the build. I will create an issue so that we don't forget to check what's going on.

**Comment by DavideD** [comment]
Well, it fixes the build for MariaDB, I still have to figure out what's going on with Db2

**Pull request merged**
