### PR TITLE
proposed fix to Vertx 4 tx handling

### PR DESCRIPTION
**Pull request by gavinking**
@DavideD can you check that this is what we should be doing.

### CODE REVIEW

**Comment by DavideD** [comment]
I think you are right.
I will see if I can add a test to check this case

**Comment by DavideD** [comment]
I'm going to apply this directly to Sanne's pr

**Comment by gavinking** [comment]
@DavideD merge this?

**Comment by DavideD** [comment]
Rebased and merged

Thanks

**Comment by gavinking** [comment]
Cheers.

**Pull request closed without merging**
