### PR TITLE
threadbound sessions

### PR DESCRIPTION
**Pull request by gavinking**
Rebase of #779.

### CODE REVIEW

**Comment by gavinking** [comment]
Alright, so in my opinion this is now done and can be merged. I'm rather happy with it.

OTOH, I really don't know what's going on with the CI :-(

**Comment by DavideD** [comment]
> OTOH, I really don't know what's going on with the CI :-(

It's because it is testing with the latest snapshots of ORM. They contain some breaking changes the we will fix in Reactive as soon as they release.

It's related to @Sanne optimizations regarding the event listeners

**Comment by DavideD** [comment]
The `Hibernate Reactive CI workflow` is the important one: https://github.com/hibernate/hibernate-reactive/pull/787/checks?check_run_id=2655014285

**Comment by gavinking** [comment]
OK then, so the important tests seem to pass.

I'm going to merge this.

**Pull request merged**
