### PR TITLE
add setHint() and overloaded setLockMode() to Query

### PR DESCRIPTION
**Pull request by gavinking**
For @FroMage and Panache.

See #217.

### CODE REVIEW

**Comment by gavinking** [comment]
I have literally *no clue* if these method will actually do anything, but I'm relying on @FroMage to let me know.

**Comment by gavinking** [comment]
Well, I added tests for `setLockMode()` so now I know one thing worx.

**Comment by FroMage** [comment]
Thanks!

**Comment by gavinking** [comment]
> Thanks!

If you actually tell me what you want to pass to `setHint()`, then I can add a test for that....

**Comment by FroMage** [comment]
Huh, I'm not sure. Our test suite has this: `setHint(QueryHints.HINT_CACHEABLE, "true")`. Does this help?

**Comment by gavinking** [comment]
> Does this help?

Well, I don't think we support query caching at all right now....

**Comment by gavinking** [comment]
So looking over the options in `QueryHints`, I'm really not sure we want to support hints for now.

Most of that stuff that we *do* support can already be set via typesafe methods.

**Comment by gavinking** [comment]
I've applied this pull, but I didn't expose `setHint()` for now, waiting for @FroMage to tell me what he wants to do with it and convince me we really want it.

**Pull request merged**
