### PR TITLE
Add log message about Vert.x at start up

### LINKED ISSUE #1134: Add log message for when we create a new Vert.x instance
Should we also have one for when we recognize that there is a Vert.x instance already?
Maybe one as info level and the other as debug.

### PR DESCRIPTION
**Pull request by DavideD**
Fixes #1134 
    
* If not detected:
  `[INFO] HR000002: Vert.x not detected, creating a new instance`
* if detected:
  `[DEBUG] Vert.x instance detected`

### CODE REVIEW

**Review by gavinking — APPROVED** [review]

**Comment by gavinking** [comment]
Should we have codes for the debug messages?

**Comment by DavideD** [comment]
As far as I know, anything from debug and under doesn't need to have code.
That said, I'm not against it in principle but this debug message doesn't seem super helpful and most people won't see it.
Not sure if a code in this case would be helpful

**Comment by DavideD** [comment]
I'm happy to move it to INFO level so that we always print something

**Comment by gavinking** [comment]
No no, just wanted to make sure we were being consistent. Don't recall what we do with other debug-level log messages.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/1142

**Pull request merged**
