### PR TITLE
link to Vert.x howto

### PR DESCRIPTION
**Pull request by gavinking**
https://how-to.vertx.io/hibernate-reactive-howto/

### CODE REVIEW

**Comment by gavinking** [comment]
@jponge did you write this?

If so: thanks 🙏

**Comment by jponge** [comment]
Yes I did :-)

**Comment by DavideD** [comment]
Thanks!
Is the project in the how-to available somewhere?

**Comment by DavideD** [comment]
Found it. Thanks

**Comment by DavideD** [comment]
By the way, the link to the source code at the top of the page  of the how-to (https://how-to.vertx.io/hibernate-reactive-howto/)
doesn't work for me, it goes to github.com and ask to login if I'm not already

**Pull request merged**
