### PR TITLE
Test against JDK17 EA

### PR DESCRIPTION
**Pull request by yrodiere**

### CODE REVIEW

**Comment by yrodiere** [comment]
Maybe we should stop testing JDK15 now that 16 is GA, but personally I'd wait until Quarkus starts running their CI against JDK16.

**Comment by yrodiere** [comment]
(JDK15 will EOL in about two weeks: https://endoflife.date/java)

**Comment by DavideD** [comment]
> Maybe we should stop testing JDK15 now that 16 is GA, but personally I'd wait until Quarkus starts running their CI against JDK16.


I think we can wait.

**Comment by yrodiere** [comment]
Looks like the Github action used to fetch the JDK does not provide JDK16 GA yet. Understandable, it's rather soon. I reverted part of my commit to only add JDK17 to the matrix.

**Comment by DavideD** [comment]
Merged https://github.com/hibernate/hibernate-reactive/pull/664

Thanks!

**Comment by gavinking** [comment]
Why did this commit check in jpamodelgen-generated code?

**Comment by yrodiere** [comment]
No idea... ? I just changed the Github config in my IDE.

**Comment by yrodiere** [comment]
Some missing entries in .gitignore, maybe?

**Comment by DavideD** [comment]
My bad, I didn't notice

**Comment by DavideD** [comment]
I will update the .gitignore

**Comment by DavideD** [comment]
> Some missing entries in .gitignore, maybe?

We updated the folders structure of the example and our rule wasn't generic enough.

I'm surprised they have been generated in the `src` folder and not in the `build` one though.
The fact that we had a rule implies it's not the first time it happens.

**Comment by yrodiere** [comment]
> > Some missing entries in .gitignore, maybe?
> 
> We updated the folders structure of the examples and our rule wasn't generic enough.
> 
> I'm surprised they have been generated in the `src` folder and not in the `build` one though.
> The fact that we had a rule implies it's not the first time it happens.

Right, something must have gone wrong... maybe IDEA generating sources before it updated its metadata based on Gradle's? I hadn't worked on HR for a while.

Sorry about that, I'll be more careful next time.

**Pull request merged**
